### ISSUE TITLE
API endpoint does not work for 7tv anymore

### ISSUE THREAD

**Issue by codeHusky** [CalebBabin/twitch-chat-emotes#13]
returns invalid data for 7tv emotes

https://gif-emotes.opl.io/v2/gif/7tv/60a7c690a004b53525b44b06.gif returns a broken gif

**Comment by CalebBabin** [comment]
There was an error with my server after 7TV updated the API recently, I changed the endpoint to grab the correct file, it works now.

Thanks for catching this!
